# Generated by Django 3.1.7 on 2021-06-23 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_person_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detected',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
