# Generated by Django 3.1.7 on 2021-06-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_detected_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detected',
            name='person_name',
        ),
    ]
